### ISSUE TITLE
[bug] Serial number IGT mismatch?

### ISSUE THREAD

**Issue by jkosciessa** [MaCuinea/Radboud-FUS-driving-system-software#34]
The following S/Ns are on the transducers:

15287 01001
15473 01002

This is correct [here](https://github.com/Donders-Institute/Radboud-FUS-driving-system-software/blob/c3de8d820f87d8a6529ea0f31c65e7fe6ee0a63a/fus_ds_package/fus_driving_systems/igt/config/imasonic_transducers/transducer_15287_10_300kHz.ini#L5), but mismatching for 15473, [e.g., this script](https://github.com/Donders-Institute/Radboud-FUS-driving-system-software/blob/c3de8d820f87d8a6529ea0f31c65e7fe6ee0a63a/fus_ds_package/fus_driving_systems/igt/config/imasonic_transducers/transducer_15473_2x10_300kHz.ini#L5).

**Comment by jkosciessa** [comment]
Perhaps I am also confused: the current transducer list in the ```use_igt_buffer``` branch lists the following:
```
['CTX-250-009', 'CTX-250-014', 'CTX-500-006', 'CTX-250-001', 'CTX-250-026', 'CTX-500-026', 'IS_PCD15287_01001', 'IS_PCD15287_01002', 'IS_PCD15473_01001', 'IS_PCD15473_01002']
```

Do ```IS_PCD15287_01002``` and ```IS_PCD15473_01001``` exist (e.g., the 75s currently not in the lab)?

**Comment by MaCuinea** [comment]
Hi Julian, The transducer ini files contain, amongst other things, the geometry of the transducer. It is correct that the transducer files containing serial numbers 15287 1001 and 15473 1001 are also used for transducers 15287 1002 and 15473 1002, because the geometry of the 1001 and 1002 is the same.

IS_PCD15287_01001 and IS_PCD15473_01002 are currently at the DCC and the other two are in the DCCN lab, so all four do exist.
